### ISSUE TITLE
Backend/ API 수정

### ISSUE THREAD

**Issue by snaag** [good-reads/backend#5]
- [x] http://ec2-54-180-154-184.ap-northeast-2.compute.amazonaws.com/api/books/get/details/?book_id=1
   - 한 책의 모든 정보를 가져오는 API
   - img가 null이다

- [x] http://ec2-54-180-154-184.ap-northeast-2.compute.amazonaws.com/api/books/create/rate/
   - Rate 모델에 새롭게 row를 추가하는 API
   - 이 API가 평점 update(http://ec2-54-180-154-184.ap-northeast-2.compute.amazonaws.com/api/books/create/rate/)와 합쳐졌으면 좋겠다

- [x] http://ec2-54-180-154-184.ap-northeast-2.compute.amazonaws.com/api/books/cancel/rate/
   - 평점 삭제
   - 그냥 에러다

**Comment by kjw217** [comment]
1) It was working. It was just my mistake.
2) I changed it that I made it just use PUT method
3) If there is no entity in Rate table, the error occurred. So, I add the code processing the case.
